#!/usr/bin/env python3
"""pr.py — post a cliproof "proof it runs" comment on a GitHub pull request.

Bundles the captured screenshot (by URL) and an optional verify report into one
Markdown comment and posts it with `gh`. Lets reviewers see the command working
without checking out the branch.

Usage:
    python pr.py --pr 42 --image-url https://raw.githubusercontent.com/o/r/branch/.github/media/help.svg \\
        --caption "mytool --help" --verify .github/media/verify.md
    python pr.py --pr 42 --image-url URL --dry-run    # print the comment, don't post

Posting requires the `gh` CLI authenticated (`gh auth status`). Pure stdlib
otherwise. The only external program invoked is `gh`.
"""
import argparse
import os
import shutil
import subprocess
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _kernel import EXIT_SUCCESS, EXIT_ERROR, success, error, emit, default_timeout, setup_streams

MARKER = "<!-- cliproof:pr-comment -->"

setup_streams()


def build_comment(image_url, caption="", verify_md=""):
    """Assemble the PR comment Markdown (marker first for future idempotent edits)."""
    lines = [MARKER, "## 📸 cliproof — proof it runs", ""]
    if image_url:
        lines += ["![{alt}]({url})".format(alt=caption or "cliproof capture", url=image_url), ""]
    if caption:
        lines += ["> `{}`".format(caption), ""]
    if verify_md:
        lines += [verify_md.strip(), ""]
    lines += ["<sub>Generated by [cliproof](https://github.com/aks-builds/cliproof).</sub>"]
    return "\n".join(lines) + "\n"


def post_comment(pr, body, repo=None):
    """Post the comment via gh. Returns gh's exit code."""
    if shutil.which("gh") is None:
        print("pr: 'gh' CLI not found; cannot post. (use --dry-run to preview)", file=sys.stderr)
        return 1
    cmd = ["gh", "pr", "comment", str(pr), "--body", body]
    if repo:
        cmd += ["--repo", repo]
    return subprocess.run(cmd).returncode


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Post a cliproof proof comment on a PR.")
    p.add_argument("--pr", required=True, help="PR number or URL")
    p.add_argument("--image-url", required=True, help="absolute (raw) URL to the committed image")
    p.add_argument("--caption", default="", help="the command captured")
    p.add_argument("--verify", help="path to a verify.py Markdown report to include")
    p.add_argument("--repo", help="owner/repo (defaults to gh's current repo)")
    p.add_argument("--dry-run", action="store_true", help="print the comment, do not post")
    p.add_argument("--json", action="store_true", help="emit machine-readable JSON to stdout")
    p.add_argument("--timeout", type=float, default=default_timeout("pr"),
                   help="timeout in seconds")
    args = p.parse_args(argv)

    verify_md = ""
    if args.verify and os.path.exists(args.verify):
        with open(args.verify, "r", encoding="utf-8-sig") as fh:
            verify_md = fh.read()

    body = build_comment(args.image_url, args.caption, verify_md)
    if args.dry_run:
        sys.stdout.write(body)
        emit(success("pr", {"pr": str(args.pr), "posted": False}), args.json)
        return EXIT_SUCCESS

    rc = post_comment(args.pr, body, repo=args.repo)
    if rc == 0:
        emit(success("pr", {"pr": str(args.pr), "posted": True}), args.json)
        return EXIT_SUCCESS
    else:
        emit(error("pr", "post_failed", EXIT_ERROR,
                   hint="ensure gh is on PATH and authenticated"), args.json)
        return EXIT_ERROR


if __name__ == "__main__":
    raise SystemExit(main())
